### ISSUE TITLE
uanble to install with go get

### ISSUE THREAD

**Issue by ysravankumar** [zerodha/gokiteconnect#102]
I'm using latest go version 1.22.2

while installing with
`go get github.com/zerodha/gokiteconnect/v4`
getting the below error

> 'go get' is no longer supported outside a module.
> To build and install a command, use 'go install' with a version,
> like 'go install example.com/cmd@latest'
> For more information, see https://golang.org/doc/go-get-install-deprecation
> or run 'go help get' or 'go help install'.

with 
`go install -v github.com/zerodha/gokiteconnect/v4@latest`

it give below error 

> go: downloading github.com/zerodha/gokiteconnect/v4 v4.3.2
> go: downloading github.com/gocarina/gocsv v0.0.0-20180809181117-b8c38cb1ba36
> go: downloading github.com/google/go-querystring v1.0.0
> package github.com/zerodha/gokiteconnect/v4 is not a main package

with  `go install -x github.com/zerodha/gokiteconnect/v4@latest`

> get https://proxy.golang.org/github.com/@v/list
> get https://proxy.golang.org/github.com/zerodha/gokiteconnect/v4/@v/list
> get https://proxy.golang.org/github.com/zerodha/gokiteconnect/@v/list
> get https://proxy.golang.org/github.com/zerodha/@v/list
> get https://proxy.golang.org/github.com/@v/list: 404 Not Found (0.028s)
> get https://proxy.golang.org/github.com/zerodha/gokiteconnect/@v/list: 404 Not Found (0.036s)
> get https://proxy.golang.org/github.com/zerodha/gokiteconnect/v4/@v/list: 200 OK (0.037s)
> get https://proxy.golang.org/github.com/zerodha/@v/list: 404 Not Found (0.037s)
> package github.com/zerodha/gokiteconnect/v4 is not a main package

**Comment by ranjanrak** [comment]
Hello @ysravankumar,
I have responded to your query on the Kiteconnect forum [here](https://kite.trade/forum/discussion/13873/unable-to-install-api-with-go-get#latest).
