### ISSUE TITLE
OHLC is not changing in tick callback

### ISSUE THREAD

**Issue by pushand** [zerodha/gokiteconnect#14]
Volume changes but OHLC remains unchanged

this is for dish tv today
<img width="393" alt="Screenshot 2019-04-04 at 10 25 07 AM" src="https://user-images.githubusercontent.com/12893140/55530568-43a55c00-56c4-11e9-99e8-348aada368f0.png">

**Comment by vividvilla** [comment]
Are you using Websockets or Quote api call?

**Comment by pushand** [comment]
Websockets

**Comment by rhnvrm** [comment]
Closing as this is stale. Please reopen with more details if needed. Thanks.
