### ISSUE TITLE
Go get error

### ISSUE THREAD

**Issue by rachit1994** [zerodha/gokiteconnect#40]
I am getting this error when trying to install. Please HELP !

```
go get: github.com/zerodha/gokiteconnect/v3@none updating to
	github.com/zerodha/gokiteconnect/v3@v3.2.1: parsing go.mod:
	module declares its path as: github.com/zerodhatech/gokiteconnect/v3
	        but was required as: github.com/zerodha/gokiteconnect/v3
```

OS: MacOS Big Sur (Version 11.4)
go version:  go1.16.4 darwin/amd64

Tried:
```
go clean -modcache
go mod edit -replace github.com/zerodhatech/gokiteconnect/v3=github.com/zerodha/gokiteconnect/v3
```

**Comment by rhnvrm** [comment]
For now, could you please try

`go get ***@***.***`

Or

`go get github.com/zerodhatech/gokiteconnect/v3`

I'll look into a fix for this in the meanwhile.

**Comment by rachit1994** [comment]
Worked! Thanks

**Comment by rhnvrm** [comment]
This should be resolved now via https://github.com/zerodha/gokiteconnect/releases/tag/v3.3.0
