### ISSUE TITLE
Suggestion : Ticker.Serve() could return something

### ISSUE THREAD

**Issue by kalbhor** [zerodha/gokiteconnect#50]
Right now `Ticker.Serve()` doesn't seem to catch any signals/errors and doesn't return anything. We could enhance it to return an error. Maybe something similar along the lines of `func (srv *Server) ListenAndServe() error`

Even if we don't return any errors right now, it maybe nice to well define the signature and keep it open ended for the future?

**Comment by rhnvrm** [comment]
Hey

Currently `ticker.Serve()` does not error out. So it might not make sense at the moment to add `error` to the signature. Users need to implement the appropriate error callbacks which receive the errors.
