### ISSUE TITLE
Handle HoldingsAuthRequired 428 InputException 

### ISSUE THREAD

**Issue by rhnvrm** [zerodha/gokiteconnect#54]
https://kite.trade/docs/connect/v3/portfolio/#holdings-authorisation

When we do readEnvelope from gokiteconnect, we over-ride the http error code in our custom error type with exception type. So when 428 status for holdings auth comes, it gets read as InputException and gets returned as BadRequest status code.

**Comment by vividvilla** [comment]
May be we should introduce a new exception type for this so that users can handle it accordingly from their end?

**Comment by rhnvrm** [comment]
We could do this, but would it require frontend changes as the frontends would be showing appropriate error messages based on InputException?
