### ISSUE TITLE
Unknown time format error for parsing order via websocket

### ISSUE THREAD

**Issue by krsacme** [zerodha/gokiteconnect#64]
Convert `Order` object received via WebSocket to json and then convert again to `Order` object. It is throwing error as `unknown time format`

The use case is WebSocket is running in a separate executable and order socket notifications are processed in a separate executable. Both communicate using unix socket.

**Comment by rhnvrm** [comment]
Hey 

Thanks for reporting, I have added a PR at #65 that should fix this.
