### ISSUE TITLE
No depth information

### ISSUE THREAD

**Issue by dragonzurfer** [zerodha/gokiteconnect#84]
There is no depth information for any of the tokens subscribed.

```
{quote 951809 true false 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC 994 27 131528 99456 1161487 0 0 987.4 0 0 0 0 {0 999 1001.35 980.4 995.4} {[{0 0 0} {0 0 0} {0 0 0} {0 0 0} {0 0 0}] [{0 0 0} {0 0 0} {0 0 0} {0 0 0} {0 0 0}]}}
```

above is the sample for voltas. I have tested for option tokens as well getting zero on them as well.

**Comment by rhnvrm** [comment]
Hi 

Please refer to the documentation to understand the different modes offered by the websocket API.

https://kite.trade/docs/connect/v3/websocket/#modes

You can refer to the usage of SetMode in this example:

https://github.com/zerodha/gokiteconnect/blob/master/examples/ticker/ticker.go#L40

**Comment by dragonzurfer** [comment]
Oh I see thanks. The definition of Tick struct is misleading. Didn't read the docs :p
