### ISSUE TITLE
Data type mismatch of auction number

### ISSUE THREAD

**Issue by ajinasokan** [zerodha/gokiteconnect#94]
Auction number is a string in holdings

https://github.com/zerodha/gokiteconnect/blob/91146a1d7e51b256323a4b61978d4487f9ea27bd/portfolio.go#L132

but it is an int in order params

https://github.com/zerodha/gokiteconnect/blob/91146a1d7e51b256323a4b61978d4487f9ea27bd/orders.go#L77

Also Order struct is missing the Auction number field.

**Comment by ShikharY10** [comment]
Hello @ajinasokan, can i start working on this issue.

**Comment by ajinasokan** [comment]
cc: @rhnvrm @vividvilla

**Comment by rhnvrm** [comment]
@ranjanrak can you confirm if https://github.com/zerodha/gokiteconnect/commit/978f71a9d43ac3f2ca180f93c4f0018518e33055 resolved this issue? If so we can close this.

**Comment by logeshsuresh** [comment]
Hey @ajinasokan, can I work on this issue if it is still not resolved ?
